# Generated by Django 5.0.2 on 2024-02-10 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("image_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("in_stock", models.PositiveIntegerField(default=0)),
                ("available_stock", models.PositiveIntegerField(default=0)),
                ("units", models.CharField(max_length=50)),
                ("min_stock", models.PositiveIntegerField(default=0)),
                ("desired_stock", models.PositiveIntegerField(default=0)),
                ("assembly", models.BooleanField(default=False)),
                ("component", models.BooleanField(default=False)),
                ("purchasable", models.BooleanField(default=False)),
                ("salable", models.BooleanField(default=False)),
                ("total_allocated", models.PositiveIntegerField(default=0)),
                ("allocated_to_builds", models.PositiveIntegerField(default=0)),
                ("allocated_to_sales", models.PositiveIntegerField(default=0)),
                ("incoming_stock", models.PositiveIntegerField(default=0)),
                ("net_stock", models.PositiveIntegerField(default=0)),
                ("can_build", models.PositiveIntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.category",
                    ),
                ),
                ("tags", models.ManyToManyField(to="backend.tag")),
            ],
        ),
    ]
