# Generated by Django 5.0.2 on 2024-02-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="assembly",
            new_name="can_assemble",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="component",
            new_name="is_bundle",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="purchasable",
            new_name="is_component",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="salable",
            new_name="is_purchasable",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="image_url",
        ),
        migrations.AddField(
            model_name="item",
            name="is_salable",
            field=models.BooleanField(default=False),
        ),
    ]
